name: Build and Deploy to Coolify

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_ACCESS_TOKEN: ${{ secrets.GHCR_ACCESS_TOKEN }}
          GEODB_CITIES_BASE_URL: ${{ secrets.GEODB_CITIES_BASE_URL }}
          GEODB_CITIES_HOST: ${{ secrets.GEODB_CITIES_HOST }}
          GEODB_CITIES_KEY: ${{ secrets.GEODB_CITIES_KEY }}
        run : ./deploy/push_image.sh
      - name: Notifies Coolify
        env:
          COOLIFY_API_TOKEN: ${{ secrets.COOLIFY_API_TOKEN }}
          COOLIFY_WEBHOOK: ${{ secrets.COOLIFY_WEBHOOK }}
        run: ./deploy/notify.sh