name: Build and Deploy to Coolify

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHRC_ACCESS_TOKEN: ${{ secrets.GHRC_ACCESS_TOKEN }}
        run : ./push_image.sh